### ISSUE TITLE
Can not open the dashboard

### ISSUE THREAD

**Issue by KimRoos** [Panther-X/PantherDashboard#1]
For some reason I can not open the dashboard in my LAN. In the web browser I get the following error message "This site can´t be reached, 192.168.0.13 refused to connect". I can ping the ip, but looks like the port 80 or 443 is somehow closed. I have tested every setting on the switch.

**Comment by jimbowarrior** [comment]
exactly the same for me !!! please investigate

**Comment by qinfengling** [comment]
Please summit the SN and more information in Panther.global. thanks

**Comment by qinfengling** [comment]
We will work hard to make it works on every Panther X2.
