### ISSUE TITLE
 There is a way to install it on the Panther X2 CN470

### ISSUE THREAD

**Issue by yuzg-test** [Panther-X/PantherDashboard#11]
The CN470 version has not released the dashboard, can I manually install the dashboard on the Panther X2？
I found that the device SSH is open, but I don't have the password or public key, is there any other way?

**Comment by qinfengling** [comment]
@yuzg-test Thanks for your question.
Sorry, we can't support it on CN470. because the GitHub repo was blocked by GFW.
