### ISSUE TITLE
Docker is not Starting anymore

### ISSUE THREAD

**Issue by Seppy001** [Panther-X/PantherDashboard#16]
Hello,

i have the Problem that the Docker from My Panther X2 don't start anymore.
The Remote IP Dind't displayed.
When i want to Update the Dashboard the Miner didnt go over the state of: "Acquiring and starting latest docker version..."

And when i want to clear the data from the Blockchain the Output is: 
"Stopping currently running docker...
Clearing Blockchain folders...
------------------------------------------
Miner docker failed to start.  Check logs to investigate."

Can some one pls help me.
thx!

**Comment by qinfengling** [comment]
please check with the [0.2.15](https://github.com/Panther-X/PantherDashboard/commit/23d6b5fa00fc3145c2787ae19bd6745d87cd9645), we should fix the issue. if it is not work for you. please sumbit the ticket in https://panther.global/

**Comment by qinfengling** [comment]
Thanks for your feedback, we found the log folder is missing in some of Panthers. we will fix in the next release.
