### ISSUE TITLE
Overlaping of informations with 2.15

### ISSUE THREAD

**Issue by JULDU74** [Panther-X/PantherDashboard#17]
![Screenshot_20220317-175929_Brave](https://user-images.githubusercontent.com/101822996/158855393-4a39bff3-e937-4d16-a5fe-0bccb4d770c2.jpg)

**Comment by qinfengling** [comment]
@JULDU74 Thanks for your feedback. Is that a mobile browser ?

**Comment by JULDU74** [comment]
@qinfengling yes it is but now it's fine, probably just an explorer refreshing matter. Thanks

**Comment by qinfengling** [comment]
great.  the current UI framework is work well with some mobile browser. we only test it with Chrome on PC.
