### ISSUE TITLE
Still synced since 6 days ago, while need to resync for port forwarding

### ISSUE THREAD

**Issue by Jreij1989** [Panther-X/PantherDashboard#18]
Dear, i got the panther x2 last 6 days ago, it got synced after 1 day but it gave relayed. So i fix the issue of port forwarding and the port is open, but the panther x2 still relayed since 6 days ago. I am trying "fast resyncing" and i tried clear blockchain data, and still relayed and syncing since 6 days ago. I need to fix it to start mining perfectly.
Thank you

**Comment by qinfengling** [comment]
@Jreij1989 Hi, Did you solve the issue ? If not, please submit your ticket in https://panther.global/ and keep it online, the technical support will help you to fix it.
