### ISSUE TITLE
Dashboard is unavailable

### ISSUE THREAD

**Issue by hajlender89** [Panther-X/PantherDashboard#19]
Hello... I have two new miners and from the start they cannot open dashboard... I tried many browsers also check firewall and all other things and the problem cannot resolve... Panther support is very lazy, Im still waiting for help.... I also tried to acces via putty but also without success because password admin doesnt work..... Before 1 weeks I also have the same problem with panther x2 mineer and that one of their tech fix it with anydesk and putty acces... any option to fix this problem on my new miners ?

**Comment by qinfengling** [comment]
@hajlender89 please submit your ticket in https://panther.global/ and keep it online, the technical support will help you to fix it.
