### ISSUE TITLE
I Can not open dashboard. My hotspot firmware 2022.01.29.0

### ISSUE THREAD

**Issue by anilokur** [Panther-X/PantherDashboard#2]
my hotspot version shows as 2022.01.29.0 in my diagnostic report. I try to enter the local ip address of my device, but the dashboard does not open. I get the following error message “This site can´t be reached, 192.168.1.51 refused to connect.” i tryed chrome, firefox and opera browser. i can not open dashboard

**Comment by hexakafa** [comment]
+1

**Comment by anilokur** [comment]
my problem is solved thanks

**Comment by hexakafa** [comment]
> ion shows as 2022

nasıl çözüldü _

**Comment by anilokur** [comment]
> > ion shows as 2022
> 
> nasıl çözüldü _

Cihaz seri numaramı istemişlerdi sonra sorunu düzelttiklerini söyleyip kontrol etmemi istediler kontrol ettiğimde sorunsuz giriş yaptım

**Comment by hexakafa** [comment]
> > > ion shows as 2022
> > 
> > 
> > nasıl çözüldü _
> 
> Cihaz seri numaramı istemişlerdi sonra sorunu düzelttiklerini söyleyip kontrol etmemi istediler kontrol ettiğimde sorunsuz giriş yaptım

seri numaranı istedikleri mail adresini verebilir misin rica etsem.

**Comment by anilokur** [comment]
> > > > ion shows as 2022
> > > 
> > > 
> > > nasıl çözüldü _
> > 
> > 
> > Cihaz seri numaramı istemişlerdi sonra sorunu düzelttiklerini söyleyip kontrol etmemi istediler kontrol ettiğimde sorunsuz giriş yaptım
> 
> seri numaranı istedikleri mail adresini verebilir misin rica etsem.

Panther.global deki destek kısmından yazdım oradan dönüş yaptılar.
