### ISSUE TITLE
Miner does not work after a click on Update Miner Docker

### ISSUE THREAD

**Issue by jmantelle** [Panther-X/PantherDashboard#20]
the miner seems to not present after an update :

the dashboard does not show the versions on the upgrade page :

Updating from: Updating to: 

Awaiting start...

in the log I see that :

Apr 19 10:02:32 Panther-X2 service-miner.sh[12711]: Error: No such object: helium-miner
Apr 19 10:02:37 Panther-X2 service-miner.sh[12856]: Error: No such object: helium-miner
Apr 19 10:02:42 Panther-X2 miner.sh[13010]: Error: No such object: helium-miner
Apr 19 10:02:42 Panther-X2 systemd[1]: miner-check.service: Failed with result 'exit-code'.
Apr 19 10:02:42 Panther-X2 service-miner.sh[13065]: Error: No such object: helium-miner

**Comment by jmantelle** [comment]
I resolved the issues with these command ( with ssh connection ) 

name="miner-update"
service=$(cat /var/dashboard/services/$name | tr -d '\n')
pantherx_ver=$(cat /var/dashboard/statuses/pantherx_ver)
miner_data_path="/opt/panther-x2/miner_data"
touch /tmp/dashboard-$name-flag
echo 'running' > /var/dashboard/services/$name
docker rm helium-miner
echo miner-arm64_2022.02.22.0_GA > current_miner_version
echo miner-arm64_2022.03.23.1_GA > latest_miner_version
version=$(cat /var/dashboard/statuses/latest_miner_version | tr -d '\n')
docker run -d --init --ulimit nofile=64000:64000 --restart always --publish 127.0.0.1:1680:1680/udp --publish 44158:44158/tcp --name helium-miner --mount type=bind,source=${miner_data_path},target=/var/data --mount type=bind,source=${miner_data_path}/log,target=/var/log/miner --device /dev/i2c-1  --privileged -v /var/run/dbus:/var/run/dbus --mount type=bind,source=/root/helium/overlay/docker.config,target=/config/sys.config quay.io/team-helium/miner:$version >> /var/dashboard/logs/$name.log

**Comment by qinfengling** [comment]
@jmantelle Thanks for you feedback. we found a miner check issue in 0.2.16, we have fixed in 0.2.17.
If you still have problems in 0.2.17, please submit your ticket in https://panther.global/

**Comment by bdabilisim** [comment]
not copy
