### ISSUE TITLE
No witnesses after update

### ISSUE THREAD

**Issue by tmabile1** [Panther-X/PantherDashboard#21]
Once the docker was fixed from yesterday now I have no witnesses.

**Comment by qinfengling** [comment]
@tmabile1 Hi, witness is not relative with dashboard. you can find some helpful information in these links.
https://docs.helium.com/troubleshooting/understanding-witnesses
https://gristleking.com/a-rough-guide-to-helium-hotspot-placement/
https://gristleking.com/how-to-use-hotspotty-to-crush/
