### ISSUE TITLE
sync delay between the miner and explorer.helium.com

### ISSUE THREAD

**Issue by mgalmad** [Panther-X/PantherDashboard#23]
Hi 
There is a kind of sync delay between the hotspot and explorer.helium.com. I had a few witness transactions a few minutes ago, but helium explorer doesn't show it.

![image](https://user-images.githubusercontent.com/50666228/164135856-a234d3c4-d2a2-4cf9-bc66-5d85bd547165.png)

the last transaction was 2 hours ago
![image](https://user-images.githubusercontent.com/50666228/164135984-aa9aa7b5-5436-4f2e-8664-97dc22c690b7.png)
could you please tell me what is going on? because that leads to the loss of witnesses 
Thanks in advanced

**Comment by mgalmad** [comment]
after 4 hours i got a witness
Please check the attached photos
![image](https://user-images.githubusercontent.com/50666228/164151737-5c9ed3a8-5133-4812-9de6-a358d08f58e9.png)
![image](https://user-images.githubusercontent.com/50666228/164151827-eeb45dd0-11a7-44f5-9c67-8eceda6eb8be.png)
![image](https://user-images.githubusercontent.com/50666228/164151971-0027c5cd-6af5-4bc5-97d1-ab8a05a7fac6.png)

**Comment by qinfengling** [comment]
Acutally, It is a helium issue. You can submit the issue in https://github.com/helium/explorer

I give a little description about that.
1. helium miner work with key-value database, so it can show the txns in realtime
2. explorer.helium.com get the txns from blockchain-etl, it is a relational database, so it need to rebuild the data structure from the key-value database.
3. explorer.helium.com is also a server, it serve a lot of client. so it also take much more time than miner.

Anyway, If you want to see it instantly or quickly. you can try to setup your own explorer instance.

**Comment by mgalmad** [comment]
could you please tell me how can I set up my own explorer instance?

**Comment by mgalmad** [comment]
it doesn't work
please check the below photo

![image](https://user-images.githubusercontent.com/50666228/164885210-2d38c18c-a983-4905-af1d-f688f2502a96.png)

**Comment by mgalmad** [comment]
![image](https://user-images.githubusercontent.com/50666228/164885747-a99366e9-c3a8-4747-b350-2605a90af270.png)
please check the error above
