### ISSUE TITLE
feautre request " Allow to install openvpn client"

### ISSUE THREAD

**Issue by mgalmad** [Panther-X/PantherDashboard#24]
Hi
Could you please push an update to allow us to install the OpenVPN client in the miner? or the miner comes with a pre-installed OpenVPN client, and the user can upload the VPN client config file web page and press connect to connect the miner with his VPN/VPS

**Comment by qinfengling** [comment]
It is not very easy, the current SDK is not work stable with the tun module, so we didn't support in the pre-install firmware.
We may release some guide for OpenVPN users. but we can't support much more.

**Comment by mgalmad** [comment]
An OpenVPN guide would be great. thanks a lot
