### ISSUE TITLE
Installing Dashboard thru SSH

### ISSUE THREAD

**Issue by alfrose** [Panther-X/PantherDashboard#27]
I entered the remove command after the yesterday firmware and removed my hotspot dashboard.
![A1BC8957-608D-4AA2-BB56-FEC3AC8E9DB0](https://user-images.githubusercontent.com/104089316/164274070-c89379cc-567c-403a-8dfa-f8d75152d386.jpeg)

Please, can anyone help me and write the command for me to enter and install the dashboard thru SSH.

thanks,
Al

**Comment by alfrose** [comment]
I got the solution, if anyone needs it.
Log in via SSH (either PuTTY or click start > type "cmd" and press enter, then type "ssh admin@your-miner-ip"). Run the following commands: wget https://raw.githubusercontent.com/Panther-X/PantherDashboard/main/install.sh -O - | sudo bash

**Comment by qinfengling** [comment]
@alfrose We have update the README for installation. please check it here: 
https://github.com/Panther-X/PantherDashboard#installation--upgrade-instructions
I hope it can help you.
