### ISSUE TITLE
安装时报错，错误如下

### ISSUE THREAD

**Issue by yuzg-test** [Panther-X/PantherDashboard#28]
安装所使用的命令：wget https://raw.githubusercontent.com/Panther-X/PantherDashboard/main/install.sh -O - | sudo bash
报错：
bash: line 43: test: too many arguments
cp: cannot stat 'dashboard/logs/*': No such file or directory
Failed to disable unit: Unit file helium-status-check.timer does not exist.

**Comment by qinfengling** [comment]
@yuzg-test Thanks for your feedback, we have fix it in 0.2.19. Please upgrade to the latest.
