### ISSUE TITLE
wget: unable to resolve host address ‘raw.githubusercontent.com’ 

### ISSUE THREAD

**Issue by jonas0567** [Panther-X/PantherDashboard#31]
Installation of Dashboard is not working. I tried this code: "wget https://raw.githubusercontent.com/Panther-X/PantherDashboard/main/install.sh -O - | sudo bash" 

but the out put is this:
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘raw.githubusercontent.com’

Miner is offline and status light is always blinking. It's already been 2 weeks.

**Comment by qinfengling** [comment]
@jonas0567 It looks the domain name(raw.githubusercontent.com) was blocked by your network settings. If your miner is still can connect to the network,  please check the firewall setting in your network
