### ISSUE TITLE
some witnesses are missing issue or not being synced

### ISSUE THREAD

**Issue by mgalmad** [Panther-X/PantherDashboard#32]
I hope you are doing well.
 
I have an issue with witnesses. Some of them are missing or not being synced with Helium explorer. 
 
Please check the video link below for the explanation.
https://loom.com/share/8ffcf7622d72401abaecd9f46643db17
![image](https://user-images.githubusercontent.com/50666228/165456303-8b3ae1e9-8ee6-466e-93e3-aca9797c9c90.png)

**Comment by Alirezauuu1850** [comment]
after this update my miner have gone offline and syncing now 11 days is it shows off and nobody response

**Comment by dagardess** [comment]
when i update my panther x2 
[Dashboard](https://github.com/Panther-X/PantherDashboard) Version: 0.2.18
Miner Version: miner-arm64_2022.05.13.0_GA
Panther X Firmware Version: 1.0.4


it have been offline the light of helium is 
blinking

**Comment by qinfengling** [comment]
@mgalmad @Alirezauuu1850 We pack the original miner image in our firmware, right now no one build it from the scratch, if you still have problems with miner, please ask help from helium's discord. Thanks for your feedback

@dagardess Please summit the SN and more information in https://panther.global/. the tech support team will fix it for you. thanks
