### ISSUE TITLE
Dashboard Witness Log Not Being Stored. 

### ISSUE THREAD

**Issue by DanPantherX** [Panther-X/PantherDashboard#33]
Multiple PantherX customers are experiencing issues while their devices receiving witnesses through Helium Explorer and paid for these witnesses our dashboard Witness logs remain empty.

I can confirm this as witnessed a beacon yeaterday and logs remain empty.

Could this be looked into please. 
![unknown-18](https://user-images.githubusercontent.com/60628431/168093181-4a85010e-d203-4c64-9e34-3d9f64449809.png)
![9A0F1A3C-490D-4F43-AA37-3FFA2B7A63FF-1](https://user-images.githubusercontent.com/60628431/168093188-ab3be06a-230b-4331-84ac-6d9126139cab.jpg)
![Screen_Shot_2022-05-12_at_16 58 28](https://user-images.githubusercontent.com/60628431/168093241-ec376249-39c3-4a11-af0a-cf928a51459a.png)
![9A0F1A3C-490D-4F43-AA37-3FFA2B7A63FF](https://user-images.githubusercontent.com/60628431/168093250-22541790-824a-4cf6-ac5d-bc5e7b576ad9.jpg)
![Screenshot_20220512-145744_Discord](https://user-images.githubusercontent.com/60628431/168093294-e844f82e-7399-4183-ac6b-5a2d83a7e8d3.jpg)
![unknown-23](https://user-images.githubusercontent.com/60628431/168093302-bf89019c-3df6-477f-945a-cc556b5114ce.png)

**Comment by alimadpan** [comment]
I have exactly the same problem, soon after the recent update I had this problem and I am not witnessing at all and the log is empty.
I usually witness on average 10 to 15 beacons

**Comment by qinfengling** [comment]
We will push the new update this week. It should fix the problem. it is under the test right now.

**Comment by qinfengling** [comment]
The latest upgrade 0.2.19 has been release, it will works.
