### ISSUE TITLE
Panther x2 is booting permanently for 6 days

### ISSUE THREAD

**Issue by Dagropro** [Panther-X/PantherDashboard#34]
My Panther x2 is not receiving rewards for 6 das already after the light hotspot Update started. My Fritzbox 6660 is also not recognize the Miner anymore and it is also not possible to enter the Panther Dashboard. Do I still just have to wait? The Status Shows "active" now, before that it was "connected", but i didn't receive any rewards.
Dry Ruby Aardvark

Thanks for any help

**Comment by qinfengling** [comment]
@Dagropro 
Please summit the SN and more information in https://panther.global/. the tech support team will fix it for you. thanks

**Comment by Dagropro** [comment]
Thanks for your reply.

It is working again

Best regards

David Gropmann

qinfengling ***@***.***> schrieb am Di., 24. Mai 2022, 18:35:
