### ISSUE TITLE
change the clock settings (TimeZone)

### ISSUE THREAD

**Issue by gozalabad** [Panther-X/PantherDashboard#37]
![Capture](https://user-images.githubusercontent.com/60188686/170292815-caa07f76-7b7e-4a74-ac66-10cb1c7aa13f.PNG)
![1](https://user-images.githubusercontent.com/60188686/170292822-8e62e3f2-7475-44dd-bc0b-c0473f658c78.PNG)
![2](https://user-images.githubusercontent.com/60188686/170292824-f15a8268-3774-4647-b391-4f84d297f167.PNG)

Hi
Please change the clock settings (TimeZone)
Example:
Make Tehran 3:30
Iran 4:30
We change every 6 months
Or add to menu UTC 4:30

**Comment by qinfengling** [comment]
@gozalabad Thanks. It is  a typo in the list, we will only keep the time zone name in the next release. anyway if you set the corrent timezone to Asia/Tehran, the time should be change to GMT+4:30.

**Comment by qinfengling** [comment]
@gozalabad Thanks for your feedback, it should be fixed in 0.2.21, please check it again.
