### ISSUE TITLE
I Can not open dashboard. My hotspot firmware 2022.01.29.0

### ISSUE THREAD

**Issue by tanselsacikara** [Panther-X/PantherDashboard#4]
my hotspot version shows as 2022.01.29.0 in my diagnostic report. I try to enter the local ip address of my device, but the dashboard does not open. I get the following error message “This site can´t be reached, 192.168.1.2 refused to connect.” i tryed chrome, firefox and opera browser. i can not open dashboard

**Comment by hexakafa** [comment]
+1
