### ISSUE TITLE
Can't login dashboard

### ISSUE THREAD

**Issue by sd1894999** [Panther-X/PantherDashboard#40]
I have  a  Panther X2 (868). and when i use https://ip    I can't open the webside . one of the pather X2 web view nginx.And one of other view ERR_CONNECTION_REFUSED.

Please help me to fix it. And tell me how  can i do .
 
THX

**Comment by qinfengling** [comment]
@sd1894999 Please summit the SN and more information in https://panther.global/. the tech support team will fix it for you. thanks
