### ISSUE TITLE
Can’t access dashbord

### ISSUE THREAD

**Issue by Geoha007** [Panther-X/PantherDashboard#42]
Hello my miner is still on 2021-12-29-2 and not updating and I can’t access the dashboard error connection refused as this veersion dosen’t have a dashboard.
I emailed the tech team with no luck yet
Anything can be done?

**Comment by qinfengling** [comment]
@Geoha007 Please summit the SN and more information in https://panther.global/. the tech support team will fix it for you. thanks.
