### ISSUE TITLE
Witness / hour calculation inaccurate

### ISSUE THREAD

**Issue by pgruetter** [Panther-X/PantherDashboard#43]
In the Log Analyzer, the calculation for Total witnesses is wrong (witnesses per hour). 
It only takes into account the first and last witness from the logs and calculates the average rate per hour. 

Example:
One witness at 07:00, another one at 07:30. Then the hotspot flatlines for 2 days. Log Analyzer will still display "Total witnesses: 2 / hour" which is wrong.

The calculations should be done according to the first and last log messages overall. In the case above, you should get something like 0.04 / hour.

**Comment by qinfengling** [comment]
@pgruetter 
Thanks for your feedback, the current calculation starts from the first witness, so we have come to this conclusion.
it has 1 witness between 07:00 and 07:30 , so the rate is 2 / hour.
As the current helium network has not solved the flatline problem, once solved, this phenomenon will be normal.

**Comment by pgruetter** [comment]
Thanks for your feedback. Although even after the flatline fix, there will be hotspots with little activity. In these cases, the current calculation might be misleading. But let's see how it turns out.
