### ISSUE TITLE
Error from running "Analysis log with LoRa Packet Forwarder Analyzer"

### ISSUE THREAD

**Issue by onstat** [Panther-X/PantherDashboard#44]
Running "Analysis log with LoRa Packet Forwarder Analyzer" gives the following error on Panther-x2

Using logs in /var/log/packet-forwarder/packet_forwarder.log 
Fatal error: Uncaught Error: Call to undefined function json_decode() in /var/dashboard/pages/lorapacketforwarderanalyzer.php:163 Stack trace: #0 /var/dashboard/pages/lorapacketforwarderanalyzer.php(78): extractData('/var/log/packet...', '2000-01-01', '2030-01-01') #1 /var/dashboard/public/index.php(128): include('/var/dashboard/...') #2 {main} thrown in /var/dashboard/pages/lorapacketforwarderanalyzer.php on line 163

Dashboard Version: 0.2.20 
Miner Version: miner-arm64_2022.06.02.1_GA 
Panther X Firmware Version: 1.0.4

**Comment by onstat** [comment]
Just an update.  the error has now changed to this below?

Using logs in /var/log/packet-forwarder/packet_forwarder.log 
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/dashboard/pages/lorapacketforwarderanalyzer.php on line 144

**Comment by qinfengling** [comment]
@onstat Thanks for your feedback, it should be fixed in 0.2.21, please check it again. If you still have problems with the 0.2.21, Please summit the SN and more information in https://panther.global/. the tech support team will fix it for you. thanks
