### ISSUE TITLE
Adding hotspot problem

### ISSUE THREAD

**Issue by Ksh1256** [Panther-X/PantherDashboard#45]
Hi please help me please 
 i was trying to add my hotspot
But the app shows " Error
hotspot not found on onboarding server unable to add hotspot"

 My order number "1610054"

Serial number of the miner "HL2EU112S220787C"

**Comment by aalsayed003** [comment]
Same problem. Did you get a solution?

**Comment by qinfengling** [comment]
@Ksh1256 @aalsayed003 This is not a Dashboard issue. At present, the onboarding license of PantherX has been suspended by Helium. For specific progress, you can follow PantherX/Helium 's Discord.
