### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by 641221621** [Panther-X/PantherDashboard#48]
root@Panther-X2://root# wget https://raw.githubusercontent.com/Panther-X/PantherDashboard/main/install.sh -O - | sudo bash
--2022-06-05 08:46:28--  https://raw.githubusercontent.com/Panther-X/PantherDashboard/main/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3480 (3.4K) [text/plain]
Saving to: ‘STDOUT’

-                                                                  100%[================================================================================================================================================================>]   3.40K  --.-KB/s    in 0s      

2022-06-05 08:46:28 (12.8 MB/s) - written to stdout [3480/3480]

rm: cannot remove '/tmp/latest.tar.gz': No such file or directory
Dashboard already installed, running an update...
--2022-06-05 08:46:28--  https://raw.githubusercontent.com/Panther-X/PantherDashboard/main/update.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4494 (4.4K) [text/plain]
Saving to: ‘STDOUT’

-                                                                  100%[================================================================================================================================================================>]   4.39K  --.-KB/s    in 0s      

2022-06-05 08:46:29 (14.4 MB/s) - written to stdout [4494/4494]

Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@Panther-X2://root#

**Comment by qinfengling** [comment]
@641221621 Thanks for your feedback, it should be fixed in 0.2.21, please check it again. If you still have problems with the 0.2.21, Please summit the SN and more information in https://panther.global/. the tech support team will fix it for you. thanks

**Comment by qinfengling** [comment]
@641221621 You can use the some command to upgrade to the latest. it is `wget https://raw.githubusercontent.com/Panther-X/PantherDashboard/main/install.sh -O - | sudo bash`
