### ISSUE TITLE
Labeling all buttons on dashboard 

### ISSUE THREAD

**Issue by JuanTaco4You** [Panther-X/PantherDashboard#5]
Theres no lables for the buttons on the dashboard. You have to guess what each one does if the symbol isn't enough.

**Comment by qinfengling** [comment]
Thanks for your feedback.
If you hove the mouse on the button, it will show the tips. Does it show correctly ?

**Comment by JuanTaco4You** [comment]
Sorry I cant try im on mobile. I dont have a mouse it doesnt show anything
though on mobile.

**Comment by qinfengling** [comment]
Sorry, We can't support the mobile well in the current frontend framework. need to consider to redesgin the frontend in the future. Please use the PC for better experience.
