### ISSUE TITLE
My miner nothing to do 13 deys fletline issue no witnesses...

### ISSUE THREAD

**Issue by haykavagyan123h** [Panther-X/PantherDashboard#50]
Hello, please check my miner status, before lighets hotspots ubdate everything worked fine, after the update my miner almost does not work dumb witnesses ... I send the miner data...
![Screenshot_20220623-221329_Chrome](https://user-images.githubusercontent.com/106231746/175366899-54c38a85-54d5-4983-a882-7dc6ca7083f9.jpg)
![Screenshot_20220623-221322_Chrome](https://user-images.githubusercontent.com/106231746/175366936-fcec21a6-f148-4dca-947f-225a1874aa47.jpg)
![Screenshot_20220623-221310_Chrome](https://user-images.githubusercontent.com/106231746/175366974-d85539d2-cbe1-48e5-9844-ef2c9eedc8b2.jpg)

**Comment by qinfengling** [comment]
@haykavagyan123h Sorry, this problem has nothing to do with Dashboard. With the increasing number of hotspots on the network, and Helium has not completely solved the flatline problem, your problem should be affected. For specific resolution progress, please follow Helium's Discord channel.
