### ISSUE TITLE
LoRa Packet Forwarder Analyzer stops working if the log size gets too big

### ISSUE THREAD

**Issue by onstat** [Panther-X/PantherDashboard#55]
"Analysis log with LoRa Packet Forwarder Analyzer" stops working if the log size gets too big.  Im my case its always less than 24 hours before it fills up as I have lots of non helium lora signals hitting my aerial.

The error I get on screen is below with nothing else showing

"Using logs in /var/log/packet-forwarder/packet_forwarder.log"

Clearing my log down to a smaller size fixes the issue and the analyser starts working with the following commands

sudo su
cd /var/log/packet-forwarder/
truncate -s 5k packet_forwarder.log

This only lasts for a day though and then it stops working. any chance of a fix in later versions please?

**Comment by onstat** [comment]
update.. I just ran the command from the command line and after a short delay it runs fine!

I expect its some problem with panthers dashboard that is timing out and not returning the results after this small delay.

**Comment by onstat** [comment]
still not working after the latest dashboard update

**Comment by qinfengling** [comment]
@onstat  Thanks for your report, We found the logrotate is missing in Panther X2, so the log will get larger and larger, 
@openxzx will fix in the next release (0.2.25)
