### ISSUE TITLE
Online Status: Not Onboarded problem

### ISSUE THREAD

**Issue by stonksonur** [Panther-X/PantherDashboard#6]
my hospot is Gentle Felt Aardvark but when i loginned dashboard i see online status:not onboarded.So i can t send beacons..what can i do?

**Comment by qinfengling** [comment]
@stonksonur Does it work now ?  The status in the dashboard may not update in time, so just wait for a moment, it should works

**Comment by stonksonur** [comment]
it is working and i get panther x2 now but i cant'log in dashboard vith local ip what can i do,it passed 24 hours
