### ISSUE TITLE
no witnesses,no beacons

### ISSUE THREAD

**Issue by quinto99** [Panther-X/PantherDashboard#60]
I updated firmware trough web browser panther x1 to ver 0.2.27 7 days ago,and still no witnesses,only transfered packets,and some rewards in range 0,00000355.When will I get more witnesses and beacons and consequently rewards??

**Comment by qinfengling** [comment]
@quinto99 Hi, It is an oracle issue in Helium not in the PantherDashboard.

We supply the technical tools to verify the issue in `Tools` -> `Miner Log analyzer` and `LoRa Packet Forwader analyzer`, you will find the beacon and witness work well in lora packet forward, but it usually does not work in the miner. Helium team is fixing the issue. you can also keep update with the discord channel: https://discord.com/channels/404106811252408320/966788311148535818
