### ISSUE TITLE
Password Reset Missing Instructions and validation Issues - special character truncation

### ISSUE THREAD

**Issue by Milodal** [Panther-X/PantherDashboard#8]
After resetting default password using special characters, 30+ length and uppercase with lowercase letters and symbols, there is no validation to check if it matches requirements. Instead, a prompt is displayed accepting the password. However, the new password that is accepted truncates ANY and ALL characters after the '&' symbol. 

For example, a 30 character password such as:   9GuRb5ovb&94Ft&zXCtT%#Mqi01raR 
would actually be converted to:  9GuRb5ovb

**Comment by qinfengling** [comment]
Thanks for your feedback, we will fix that in the next release.

**Comment by Milodal** [comment]
Hi QinFengling
Not in 0.2.11 since that is the version I had when I initially changed
passwords. Also I updated to 0.2.12 and when you click on reset password,
there are no instructions that pop up telling you the restrictions and
limitations of your passwords. So no not sure what specially you fixed but
it is not showing up on user prompts.

**Comment by qinfengling** [comment]
@Milodal Thanks for your reply again. We have update the prompt in 0.2.13. keep us update if you also find any issues.

git commit url: https://github.com/Panther-X/PantherDashboard/commit/f97293bdadef04b5db3a1eba5013c85a8e4fb955
